version: "3.8"

x-environment: &env
  environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_DB=reports
  - POSTGRES_HOST=db
  - POSTGRES_PORT=5432

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    <<: *env

    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER:-postgres}", "-d", "${POSTGRES_DB:-reports}"]
      timeout: 10s
      interval: 5s
      retries: 3

  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    <<: *env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
