version: "3"

services:
  service_db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  service_tests:
    image: mytests
    build:
      context: .
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - service_db
