version: "3"

services:
  service_db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER:-postgres}", "-d", "${POSTGRES_DB:-test}"]
      timeout: 10s
      interval: 5s
      retries: 3

  service_tests:
    build:
      context: .
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      service_db:
        condition: service_healthy
