"""Initial migration

Revision ID: 05674f744f4c
Revises:
Create Date: 2023-03-13 16:00:44.279300

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05674f744f4c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=50), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timetables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("timetable", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["timetable"],
            ["timetables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subjects")
    op.drop_table("timetables")
    op.drop_table("students")
    op.drop_table("groups")
    # ### end Alembic commands ###
