"""Add email for student

Revision ID: e107821dcfe1
Revises: 05674f744f4c
Create Date: 2023-03-16 16:07:49.814390

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e107821dcfe1"
down_revision = "05674f744f4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("email", sa.String(), nullable=False))
    op.create_unique_constraint(None, "students", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "students", type_="unique")
    op.drop_column("students", "email")
    # ### end Alembic commands ###
