"""add_password_for_student

Revision ID: 34488fe8be56
Revises: 321660feb675
Create Date: 2023-03-28 15:40:15.279978

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "34488fe8be56"
down_revision = "321660feb675"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "password")
    # ### end Alembic commands ###
