name: Linters

on:
  push:
    branches: [ master ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install black

      - name: Run black
        run: poetry run black --check app

  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install isort

      - name: Run isort
        run: poetry run isort --check-only app

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install Flake8, Flake8-pyproject

      - name: Run flake8
        run: poetry run flake8 app
