name: Coverage

on:
  push:
    branches: [ master ]

jobs:
  coverage_and_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install deps
        run: poetry install --no-root

      - name: Test with pytest
        run: poetry run pytest

      - name: Coverage
        run: poetry run coverage json

      - name: Install jq
        run: sudo apt install jq

      - name: Get percent coverage
        run: |
          poetry run coverage json
          echo TOTAL=$(cat coverage.json | jq .totals | jq .percent_covered) >> $GITHUB_ENV

      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6142fbd47742665fa2e00b989f7f6935
          filename: my_coverage.json
          label: Coverage
          message: ${{ env.TOTAL }}
          valColorRange: ${{ env.TOTAL }}
          maxColorRange: 100
          minColorRange: 0
