name: Linters

on:
  push:
    branches: [ master ]

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install deps
        run: poetry install --only dev --no-root

      - name: Run black
        run: poetry run black --check app

      - name: Run isort
        run: poetry run isort --check-only app

      - name: Run flake8
        run: poetry run flake8 app
